import { db } from "./db";
import {
  campaignsTable,
  companiesTable,
  customersTable,
  employeesTable,
  orderItemsTable,
  ordersTable,
  productsTable,
  subscriptionsTable,
  supportTicketsTable,
} from "./schema";

async function main() {
  console.log("🌱 Seeding database...");

  // // Clear existing data (children first to satisfy foreign keys)
  // await db.delete(orderItemsTable);
  // await db.delete(supportTicketsTable);
  // await db.delete(subscriptionsTable);
  // await db.delete(ordersTable);
  // await db.delete(productsTable);
  // await db.delete(employeesTable);
  // await db.delete(campaignsTable);
  // await db.delete(customersTable);
  // await db.delete(companiesTable);

  // companies (10)
  await db.insert(companiesTable).values([
    { id: 1, name: "Acme Analytics", industry: "SaaS", country: "USA" },
    {
      id: 2,
      name: "Nordic Commerce",
      industry: "E-commerce",
      country: "Sweden",
    },
    {
      id: 3,
      name: "Bluefin Health",
      industry: "Healthcare",
      country: "Canada",
    },
    { id: 4, name: "Quantum Ledger", industry: "Fintech", country: "UK" },
    { id: 5, name: "GreenGrid Energy", industry: "Energy", country: "Germany" },
    {
      id: 6,
      name: "Skyline Mobility",
      industry: "Transportation",
      country: "Netherlands",
    },
    { id: 7, name: "Orbit Edu", industry: "EdTech", country: "India" },
    {
      id: 8,
      name: "Harvest Foods",
      industry: "Food & Beverage",
      country: "Australia",
    },
    { id: 9, name: "Pixel Forge", industry: "Gaming", country: "Japan" },
    {
      id: 10,
      name: "Aster Security",
      industry: "Cybersecurity",
      country: "Singapore",
    },
  ]);

  // employees (10)
  await db.insert(employeesTable).values([
    {
      id: 1,
      company_id: 1,
      name: "Olivia Carter",
      email: "olivia.carter@acme.com",
      department: "Engineering",
      role: "Software Engineer",
    },
    {
      id: 2,
      company_id: 2,
      name: "Liam Berg",
      email: "liam.berg@nordiccommerce.com",
      department: "Operations",
      role: "Operations Manager",
    },
    {
      id: 3,
      company_id: 3,
      name: "Maya Thompson",
      email: "maya.thompson@bluefinhealth.com",
      department: "Product",
      role: "Product Manager",
    },
    {
      id: 4,
      company_id: 4,
      name: "Noah Patel",
      email: "noah.patel@quantumledger.com",
      department: "Finance",
      role: "Financial Analyst",
    },
    {
      id: 5,
      company_id: 5,
      name: "Emma Schneider",
      email: "emma.schneider@greengrid.com",
      department: "R&D",
      role: "Research Scientist",
    },
    {
      id: 6,
      company_id: 6,
      name: "Lucas van Dijk",
      email: "lucas.vandijk@skylinemobility.com",
      department: "Logistics",
      role: "Logistics Lead",
    },
    {
      id: 7,
      company_id: 7,
      name: "Aarav Mehta",
      email: "aarav.mehta@orbitedu.com",
      department: "Customer Success",
      role: "CS Specialist",
    },
    {
      id: 8,
      company_id: 8,
      name: "Sophia Nguyen",
      email: "sophia.nguyen@harvestfoods.com",
      department: "Marketing",
      role: "Marketing Manager",
    },
    {
      id: 9,
      company_id: 9,
      name: "Hiro Tanaka",
      email: "hiro.tanaka@pixelforge.com",
      department: "Design",
      role: "Game Designer",
    },
    {
      id: 10,
      company_id: 10,
      name: "Zoe Lim",
      email: "zoe.lim@astersecurity.com",
      department: "Security",
      role: "Security Engineer",
    },
  ]);

  // customers (10)
  await db.insert(customersTable).values([
    {
      id: 1,
      company_id: 1,
      first_name: "Ethan",
      last_name: "Reed",
      email: "ethan.reed@example.com",
      city: "San Francisco",
      state: "CA",
      country: "USA",
      signup_date: "2025-01-05",
      status: "active",
      total_spent: 1499.5,
    },
    {
      id: 2,
      company_id: 2,
      first_name: "Isla",
      last_name: "Johansson",
      email: "isla.johansson@example.com",
      city: "Stockholm",
      state: "Stockholm",
      country: "Sweden",
      signup_date: "2025-01-08",
      status: "active",
      total_spent: 820.0,
    },
    {
      id: 3,
      company_id: 3,
      first_name: "Mason",
      last_name: "Clark",
      email: "mason.clark@example.com",
      city: "Toronto",
      state: "ON",
      country: "Canada",
      signup_date: "2025-01-12",
      status: "inactive",
      total_spent: 230.75,
    },
    {
      id: 4,
      company_id: 4,
      first_name: "Ava",
      last_name: "Shah",
      email: "ava.shah@example.com",
      city: "London",
      state: "England",
      country: "UK",
      signup_date: "2025-01-16",
      status: "active",
      total_spent: 2640.0,
    },
    {
      id: 5,
      company_id: 5,
      first_name: "Leo",
      last_name: "Keller",
      email: "leo.keller@example.com",
      city: "Berlin",
      state: "Berlin",
      country: "Germany",
      signup_date: "2025-01-20",
      status: "churned",
      total_spent: 99.99,
    },
    {
      id: 6,
      company_id: 6,
      first_name: "Mila",
      last_name: "de Vries",
      email: "mila.devries@example.com",
      city: "Amsterdam",
      state: "North Holland",
      country: "Netherlands",
      signup_date: "2025-01-22",
      status: "active",
      total_spent: 410.4,
    },
    {
      id: 7,
      company_id: 7,
      first_name: "Arjun",
      last_name: "Iyer",
      email: "arjun.iyer@example.com",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      signup_date: "2025-01-24",
      status: "active",
      total_spent: 560.0,
    },
    {
      id: 8,
      company_id: 8,
      first_name: "Charlotte",
      last_name: "Brown",
      email: "charlotte.brown@example.com",
      city: "Sydney",
      state: "NSW",
      country: "Australia",
      signup_date: "2025-01-26",
      status: "inactive",
      total_spent: 305.2,
    },
    {
      id: 9,
      company_id: 9,
      first_name: "Ren",
      last_name: "Sato",
      email: "ren.sato@example.com",
      city: "Tokyo",
      state: "Tokyo",
      country: "Japan",
      signup_date: "2025-01-28",
      status: "active",
      total_spent: 1200.0,
    },
    {
      id: 10,
      company_id: 10,
      first_name: "Nur",
      last_name: "Ong",
      email: "nur.ong@example.com",
      city: "Singapore",
      state: "Central",
      country: "Singapore",
      signup_date: "2025-01-30",
      status: "active",
      total_spent: 980.45,
    },
  ]);

  // products (10)
  await db.insert(productsTable).values([
    {
      id: 1,
      company_id: 1,
      name: "Insights Pro",
      category: "Software",
      price: 199.99,
      stock: 50,
      is_active: 1,
    },
    {
      id: 2,
      company_id: 2,
      name: "Cart Booster",
      category: "Plugin",
      price: 79.0,
      stock: 120,
      is_active: 1,
    },
    {
      id: 3,
      company_id: 3,
      name: "Care Monitor",
      category: "Device",
      price: 349.5,
      stock: 40,
      is_active: 1,
    },
    {
      id: 4,
      company_id: 4,
      name: "Ledger Sync",
      category: "Software",
      price: 129.0,
      stock: 70,
      is_active: 1,
    },
    {
      id: 5,
      company_id: 5,
      name: "Grid Optimizer",
      category: "Service",
      price: 499.0,
      stock: 20,
      is_active: 1,
    },
    {
      id: 6,
      company_id: 6,
      name: "Fleet Tracker",
      category: "Hardware",
      price: 259.0,
      stock: 35,
      is_active: 1,
    },
    {
      id: 7,
      company_id: 7,
      name: "Tutor Suite",
      category: "Software",
      price: 59.0,
      stock: 200,
      is_active: 1,
    },
    {
      id: 8,
      company_id: 8,
      name: "FreshBox Premium",
      category: "Subscription",
      price: 39.99,
      stock: 500,
      is_active: 1,
    },
    {
      id: 9,
      company_id: 9,
      name: "XP Booster Pack",
      category: "In-game",
      price: 14.99,
      stock: 1000,
      is_active: 1,
    },
    {
      id: 10,
      company_id: 10,
      name: "Threat Shield",
      category: "Security",
      price: 299.0,
      stock: 60,
      is_active: 1,
    },
  ]);

  // orders (10)
  await db.insert(ordersTable).values([
    {
      id: 1,
      company_id: 1,
      customer_id: 1,
      order_status: "completed",
      payment_status: "paid",
      total_amount: 199.99,
      order_date: "2025-02-01",
    },
    {
      id: 2,
      company_id: 2,
      customer_id: 2,
      order_status: "completed",
      payment_status: "paid",
      total_amount: 158.0,
      order_date: "2025-02-02",
    },
    {
      id: 3,
      company_id: 3,
      customer_id: 3,
      order_status: "pending",
      payment_status: "authorized",
      total_amount: 349.5,
      order_date: "2025-02-03",
    },
    {
      id: 4,
      company_id: 4,
      customer_id: 4,
      order_status: "completed",
      payment_status: "paid",
      total_amount: 258.0,
      order_date: "2025-02-04",
    },
    {
      id: 5,
      company_id: 5,
      customer_id: 5,
      order_status: "refunded",
      payment_status: "refunded",
      total_amount: 499.0,
      order_date: "2025-02-05",
    },
    {
      id: 6,
      company_id: 6,
      customer_id: 6,
      order_status: "completed",
      payment_status: "paid",
      total_amount: 518.0,
      order_date: "2025-02-06",
    },
    {
      id: 7,
      company_id: 7,
      customer_id: 7,
      order_status: "completed",
      payment_status: "paid",
      total_amount: 177.0,
      order_date: "2025-02-07",
    },
    {
      id: 8,
      company_id: 8,
      customer_id: 8,
      order_status: "pending",
      payment_status: "pending",
      total_amount: 79.98,
      order_date: "2025-02-08",
    },
    {
      id: 9,
      company_id: 9,
      customer_id: 9,
      order_status: "completed",
      payment_status: "paid",
      total_amount: 44.97,
      order_date: "2025-02-09",
    },
    {
      id: 10,
      company_id: 10,
      customer_id: 10,
      order_status: "completed",
      payment_status: "paid",
      total_amount: 598.0,
      order_date: "2025-02-10",
    },
  ]);

  // order_items (10)
  await db.insert(orderItemsTable).values([
    {
      id: 1,
      order_id: 1,
      product_id: 1,
      quantity: 1,
      unit_price: 199.99,
      total_price: 199.99,
    },
    {
      id: 2,
      order_id: 2,
      product_id: 2,
      quantity: 2,
      unit_price: 79.0,
      total_price: 158.0,
    },
    {
      id: 3,
      order_id: 3,
      product_id: 3,
      quantity: 1,
      unit_price: 349.5,
      total_price: 349.5,
    },
    {
      id: 4,
      order_id: 4,
      product_id: 4,
      quantity: 2,
      unit_price: 129.0,
      total_price: 258.0,
    },
    {
      id: 5,
      order_id: 5,
      product_id: 5,
      quantity: 1,
      unit_price: 499.0,
      total_price: 499.0,
    },
    {
      id: 6,
      order_id: 6,
      product_id: 6,
      quantity: 2,
      unit_price: 259.0,
      total_price: 518.0,
    },
    {
      id: 7,
      order_id: 7,
      product_id: 7,
      quantity: 3,
      unit_price: 59.0,
      total_price: 177.0,
    },
    {
      id: 8,
      order_id: 8,
      product_id: 8,
      quantity: 2,
      unit_price: 39.99,
      total_price: 79.98,
    },
    {
      id: 9,
      order_id: 9,
      product_id: 9,
      quantity: 3,
      unit_price: 14.99,
      total_price: 44.97,
    },
    {
      id: 10,
      order_id: 10,
      product_id: 10,
      quantity: 2,
      unit_price: 299.0,
      total_price: 598.0,
    },
  ]);

  // subscriptions (10)
  await db.insert(subscriptionsTable).values([
    {
      id: 1,
      customer_id: 1,
      plan_name: "Pro",
      monthly_price: 49.99,
      status: "active",
      start_date: "2025-02-01",
      end_date: null,
      renewal_date: "2025-03-01",
    },
    {
      id: 2,
      customer_id: 2,
      plan_name: "Growth",
      monthly_price: 29.0,
      status: "active",
      start_date: "2025-02-02",
      end_date: null,
      renewal_date: "2025-03-02",
    },
    {
      id: 3,
      customer_id: 3,
      plan_name: "Starter",
      monthly_price: 19.0,
      status: "canceled",
      start_date: "2025-02-03",
      end_date: "2025-03-03",
      renewal_date: null,
    },
    {
      id: 4,
      customer_id: 4,
      plan_name: "Enterprise",
      monthly_price: 199.0,
      status: "active",
      start_date: "2025-02-04",
      end_date: null,
      renewal_date: "2025-03-04",
    },
    {
      id: 5,
      customer_id: 5,
      plan_name: "Basic",
      monthly_price: 9.99,
      status: "trial",
      start_date: "2025-02-05",
      end_date: "2025-02-19",
      renewal_date: "2025-02-20",
    },
    {
      id: 6,
      customer_id: 6,
      plan_name: "Pro",
      monthly_price: 49.99,
      status: "active",
      start_date: "2025-02-06",
      end_date: null,
      renewal_date: "2025-03-06",
    },
    {
      id: 7,
      customer_id: 7,
      plan_name: "Growth",
      monthly_price: 29.0,
      status: "active",
      start_date: "2025-02-07",
      end_date: null,
      renewal_date: "2025-03-07",
    },
    {
      id: 8,
      customer_id: 8,
      plan_name: "Starter",
      monthly_price: 19.0,
      status: "canceled",
      start_date: "2025-02-08",
      end_date: "2025-02-28",
      renewal_date: null,
    },
    {
      id: 9,
      customer_id: 9,
      plan_name: "Pro",
      monthly_price: 49.99,
      status: "active",
      start_date: "2025-02-09",
      end_date: null,
      renewal_date: "2025-03-09",
    },
    {
      id: 10,
      customer_id: 10,
      plan_name: "Enterprise",
      monthly_price: 199.0,
      status: "trial",
      start_date: "2025-02-10",
      end_date: "2025-02-24",
      renewal_date: "2025-02-25",
    },
  ]);

  // support_tickets (10)
  await db.insert(supportTicketsTable).values([
    {
      id: 1,
      customer_id: 1,
      subject: "Unable to export report",
      status: "open",
      priority: "high",
    },
    {
      id: 2,
      customer_id: 2,
      subject: "Billing invoice mismatch",
      status: "closed",
      priority: "medium",
    },
    {
      id: 3,
      customer_id: 3,
      subject: "Device sync delay",
      status: "open",
      priority: "medium",
    },
    {
      id: 4,
      customer_id: 4,
      subject: "2FA setup issue",
      status: "closed",
      priority: "low",
    },
    {
      id: 5,
      customer_id: 5,
      subject: "Refund not received",
      status: "open",
      priority: "high",
    },
    {
      id: 6,
      customer_id: 6,
      subject: "Tracker firmware update help",
      status: "closed",
      priority: "low",
    },
    {
      id: 7,
      customer_id: 7,
      subject: "Course progress reset",
      status: "open",
      priority: "high",
    },
    {
      id: 8,
      customer_id: 8,
      subject: "Subscription cancellation",
      status: "closed",
      priority: "medium",
    },
    {
      id: 9,
      customer_id: 9,
      subject: "In-game purchase failed",
      status: "open",
      priority: "high",
    },
    {
      id: 10,
      customer_id: 10,
      subject: "Security alert false positive",
      status: "open",
      priority: "medium",
    },
  ]);

  // campaigns (10)
  await db.insert(campaignsTable).values([
    {
      id: 1,
      company_id: 1,
      name: "Q1 Lead Gen",
      platform: "google",
      budget: 5000,
      clicks: 4200,
      conversions: 320,
      start_date: "2025-01-01",
      end_date: "2025-03-31",
    },
    {
      id: 2,
      company_id: 2,
      name: "Spring Retargeting",
      platform: "meta",
      budget: 3200,
      clicks: 2800,
      conversions: 190,
      start_date: "2025-02-01",
      end_date: "2025-04-30",
    },
    {
      id: 3,
      company_id: 3,
      name: "Healthcare Awareness",
      platform: "linkedin",
      budget: 4100,
      clicks: 1900,
      conversions: 110,
      start_date: "2025-01-15",
      end_date: "2025-03-15",
    },
    {
      id: 4,
      company_id: 4,
      name: "Fintech Expansion",
      platform: "google",
      budget: 6200,
      clicks: 5100,
      conversions: 410,
      start_date: "2025-01-10",
      end_date: "2025-04-10",
    },
    {
      id: 5,
      company_id: 5,
      name: "Green Awareness",
      platform: "meta",
      budget: 2800,
      clicks: 2400,
      conversions: 140,
      start_date: "2025-02-10",
      end_date: "2025-05-10",
    },
    {
      id: 6,
      company_id: 6,
      name: "Urban Mobility",
      platform: "google",
      budget: 4700,
      clicks: 3600,
      conversions: 260,
      start_date: "2025-01-20",
      end_date: "2025-04-20",
    },
    {
      id: 7,
      company_id: 7,
      name: "Back-to-School",
      platform: "meta",
      budget: 3900,
      clicks: 3100,
      conversions: 230,
      start_date: "2025-02-05",
      end_date: "2025-05-05",
    },
    {
      id: 8,
      company_id: 8,
      name: "FreshBox Launch",
      platform: "google",
      budget: 3500,
      clicks: 2950,
      conversions: 210,
      start_date: "2025-01-25",
      end_date: "2025-03-25",
    },
    {
      id: 9,
      company_id: 9,
      name: "New Season Pass",
      platform: "meta",
      budget: 5400,
      clicks: 4800,
      conversions: 390,
      start_date: "2025-02-12",
      end_date: "2025-04-12",
    },
    {
      id: 10,
      company_id: 10,
      name: "Zero Trust Push",
      platform: "linkedin",
      budget: 4300,
      clicks: 2200,
      conversions: 160,
      start_date: "2025-01-18",
      end_date: "2025-04-18",
    },
  ]);

  console.log("✅ Database seeded successfully!");
}

main()
  .then(() => {
    console.log("Seed completed");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });

export { main };
